<?xml version="1.0" encoding="utf-8"?><Database Name="ZGF_Revit_Content" Class="RevitContentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=pdx-sql-3;Initial Catalog=ZGF_Revit_Content;Integrated Security=True" SettingsObjectName="RevitContentWatcher.Properties.Settings" SettingsPropertyName="ZGF_Revit_ContentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RevitContentMain" Member="RevitContentMains">
    <Type Name="RevitContentMain">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FolderSearchTerm" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="FullPathName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FileVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PreviewImage" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FileSize" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>